### ISSUE TITLE
Issue while plotting my data in R

### ISSUE THREAD

**Issue by thesnakeguy** [dipetkov/eems#10]
Hi,

When trying to plot my graph I get this R error: "Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘coordinates’ for signature ‘"numeric". What could lead to this error and how to fix this?

additional info that doesn't seem right when running the eems analysis in the terminal:
There are 1 observed demes (out of 172 demes)
The population grid has 172 demes and 444 edges
There are 792 samples assigned to 1 observed demes

Many thanks

**Comment by dipetkov** [comment]
No, it doesn't seem right -- you can see that the population grid gets constructed but all samples get assigned to the same deme. To get help, you could provide some more information about your input to `runeems`. Otherwise, my first suggestion is to check that the coordinates in the `coord` and `outer` file are specified consistently: either (longitude, latitude) in both or (latitude, longitude) in both.

Similar comment about the plotting function -- first make sure that all required packages are installed properly. Google tells me that the error above is associated with the `sp` package. Or perhaps one of the other spatial packages required: `rgeos`, `raster`.

**Comment by thesnakeguy** [comment]
Thanks a lot! Indeed, the coord and outer file weren't consistent. My problem is solved now.
