### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by nehasavant** [dipetkov/eems#31]
Hi Dr. Petkova, 

I'm having trouble with installing bed2diffs properly. I've downloaded the EEMS files and the plinkio files from Github (I put both master directories in one folder labeled "EEMS"). Then I edited the PLINKIO variable in the makefile in "src-wout-openmp" (I'm working on a Mac) to  where I've downloaded the "libplinkio-master" directory. However, I'm getting this error when I run ```make darwin``` in terminal within the src-wout-openmp directory: 

```
Nehas-MacBook-Pro:src-wout-openmp nehasavant$ make darwin
c++ -I/Users/nehasavant/Dropbox/Columbia_New_York/Salamanders/Downstream_Analyses/EEMS/libplinkio-master//include -O3 -Wall -Werror -c bed2diffs_v1.cpp -o bed2diffs_v1.o
In file included from bed2diffs_v1.cpp:3:
./data.hpp:7:10: fatal error: 'plinkio/plinkio.h' file not found
#include <plinkio/plinkio.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [bed2diffs_v1.o] Error 1
```

I'm not quite sure what I'm doing wrong. Any thoughts or advice would be much appreciated! 

Thank you, 
Neha

**Comment by dipetkov** [comment]
Thanks for pointing this out. You are right that with the latest version of libplinkio, it is necessary to change the line
```
CXXFLAGS = -I${PLINKIO}/include -O3 -Wall -Werror
```
to
```
CXXFLAGS = -I${PLINKIO} -O3 -Wall -Werror
```
in the Makefile of bed2diffs.

Since libplinkio is on GitHub you can also get any older version by checking out its corresponding commit. For example, the current commit is 781e9ee37076... and to use that version of libplinkio in the future:
```
git clone https://github.com/mfranberg/libplinkio
cd libplinkio
git checkout 781e9ee37076
```

This should work now with bed2diffs since I've updated the c++ flags in the Makefile.
